source 'http://rubygems.org'

gem 'rails',            '~> 3.0'
gem 'unicorn',          '~> 3.4'
gem 'capistrano',       '~> 2.5'
gem 'ruby-debug19',     '~> 0.11'
gem "jquery-rails",     '~> 0.2'
gem 'mongoid',          '~> 2.0'
gem 'bson_ext',         '~> 1.2'
gem 'carrierwave',      '~> 0.5'
gem 'rack-gridfs',      '~> 0.4'
gem 'devise',           '~> 1.1'
gem 'redis',            '~> 2.2'
gem 'redis-namespace',  '~> 0.10'
gem 'chronic',          '~> 0.4'

group :development, :test do
  gem 'rspec-rails',       '~> 2.5'
  gem 'rr',                '~> 1.0'
  gem 'capybara',          :git => 'git://github.com/jnicklas/capybara.git'
  gem 'akephalos',         '~> 0.2'
  gem 'mongoid-rspec',     '~> 1.4'
  gem 'database_cleaner',  '~> 0.6'
  gem 'evergreen',         '~> 0.4'
  gem 'rocco',             '~> 0.5'
  gem 'pygmentize',        '~> 0.0.2'
end
